[package]
name = "namenpesel-gen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
file_indexing = "0.4.0"
scanrs = "0.3.0"
iced = "0.3.0"